[#127] Replace xmlrunner with unittest-xml-reporting
The pip package for xmlrunner should be installed via the
unittest-xml-reporting package instead of xmlrunner. xmlrunner is
supported for python2, so the package will remain the same for platforms
which support iRODS versions which use python2.

Also, aligned release Dockerfiles with regular Dockerfiles such that
build caches can be leveraged.

diff --git a/projects/almalinux-8/Dockerfile b/projects/almalinux-8/Dockerfile
--- a/projects/almalinux-8/Dockerfile
+++ b/projects/almalinux-8/Dockerfile
@@ -1,43 +1,50 @@
 FROM almalinux:8
 
-RUN \
-  yum update -y && \
-  yum install -y \
-    authd \
-    epel-release \
-    gcc-c++ \
-    gnupg \
-    make \
-    python3 \
-    python3-pip \
-    rsyslog \
-    sudo \
-    unixODBC-devel \
-    wget \
-    which \
-    diffutils \
-  && \
-  yum clean all && \
-  rm -rf /var/cache/yum /tmp/*
-
-# python 2 and 3 must be installed separately because yum will ignore/discard python2
-RUN \
-  yum check-update -q >/dev/null || { [ "$?" -eq 100 ] && yum update -y; } && \
-  yum install -y \
-    python3 \
-    python3-devel \
-    python3-pip \
-  && \
-  yum clean all && \
-  rm -rf /var/cache/yum /tmp/*
-
-RUN python3 -m pip install xmlrunner distro psutil pyodbc jsonschema requests
+RUN yum check-update -q >/dev/null || { [ "$?" -eq 100 ] && yum update -y; } && \
+    yum install -y \
+        ca-certificates \
+        epel-release \
+        gnupg \
+        wget \
+    && \
+    yum clean all && \
+    rm -rf /var/cache/yum /tmp/*
 
 RUN rpm --import https://packages.irods.org/irods-signing-key.asc && \
     wget -qO - https://packages.irods.org/renci-irods.yum.repo | tee /etc/yum.repos.d/renci-irods.yum.repo
 
 RUN rpm --import https://core-dev.irods.org/irods-core-dev-signing-key.asc && \
     wget -qO - https://core-dev.irods.org/renci-irods-core-dev.yum.repo | tee /etc/yum.repos.d/renci-irods-core-dev.yum.repo
+
+# TODO: For some reason, this makes the build fail after adding the iRODS repo
+#RUN yum check-update -q >/dev/null || { [ "$?" -eq 100 ] && yum update -y; } && \
+RUN yum update -y && \
+    yum install -y \
+        authd \
+        diffutils \
+        gcc-c++ \
+        make \
+        rsyslog \
+        sudo \
+        unixODBC-devel \
+        which \
+    && \
+    yum clean all && \
+    rm -rf /var/cache/yum /tmp/*
+
+# python 2 and 3 must be installed separately because yum will ignore/discard python2
+# TODO: For some reason, this makes the build fail after adding the iRODS repo
+#RUN yum check-update -q >/dev/null || { [ "$?" -eq 100 ] && yum update -y; } && \
+RUN yum update -y && \
+    yum install -y \
+        python3 \
+        python3-devel \
+        python3-pip \
+    && \
+    yum clean all && \
+    rm -rf /var/cache/yum /tmp/*
+
+RUN python3 -m pip install unittest-xml-reporting distro psutil pyodbc jsonschema requests
 
 COPY rsyslog.conf /etc/rsyslog.conf
 
diff --git a/projects/centos-7/Dockerfile b/projects/centos-7/Dockerfile
--- a/projects/centos-7/Dockerfile
+++ b/projects/centos-7/Dockerfile
@@ -1,52 +1,14 @@
 FROM centos:7
 
-RUN \
-  yum update -y && \
-  yum install -y \
-    authd \
-    epel-release \
-    gcc-c++ \
-    gnupg \
-    make \
-    python \
-    python-pip \
-    python3 \
-    python3-pip \
-    rsyslog \
-    sudo \
-    unixODBC-devel \
-    wget \
-    which \
-  && \
-  yum clean all && \
-  rm -rf /var/cache/yum /tmp/*
-
-# python 2 and 3 must be installed separately because yum will ignore/discard python2
-RUN \
-  yum check-update -q >/dev/null || { [ "$?" -eq 100 ] && yum update -y; } && \
-  yum install -y \
-    python3 \
-    python3-devel \
-    python3-pip \
-  && \
-  yum clean all && \
-  rm -rf /var/cache/yum /tmp/*
-
-RUN pip3 install xmlrunner distro psutil pyodbc jsonschema requests
-
-RUN \
-  yum check-update -q >/dev/null || { [ "$?" -eq 100 ] && yum update -y; } && \
-  yum install -y \
-    python \
-    python-devel \
-    python-distro \
-    python-pip \
-    python-requests \
-    python-jsonschema \
-    python-psutil \
-  && \
-  yum clean all && \
-  rm -rf /var/cache/yum /tmp/*
+RUN yum check-update -q >/dev/null || { [ "$?" -eq 100 ] && yum update -y; } && \
+    yum install -y \
+        ca-certificates \
+        epel-release \
+        gnupg \
+        wget \
+    && \
+    yum clean all && \
+    rm -rf /var/cache/yum /tmp/*
 
 RUN rpm --import https://packages.irods.org/irods-signing-key.asc && \
     wget -qO - https://packages.irods.org/renci-irods.yum.repo | tee /etc/yum.repos.d/renci-irods.yum.repo
@@ -54,7 +16,53 @@ RUN rpm --import https://packages.irods.org/irods-signing-key.asc && \
 RUN rpm --import https://core-dev.irods.org/irods-core-dev-signing-key.asc && \
     wget -qO - https://core-dev.irods.org/renci-irods-core-dev.yum.repo | tee /etc/yum.repos.d/renci-irods-core-dev.yum.repo
 
+# TODO: For some reason, this makes the build fail after adding the iRODS repo
+#RUN yum check-update -q >/dev/null || { [ "$?" -eq 100 ] && yum update -y; } && \
+RUN yum update -y && \
+    yum install -y \
+        authd \
+        gcc-c++ \
+        make \
+        rsyslog \
+        sudo \
+        unixODBC-devel \
+        which \
+    && \
+    yum clean all && \
+    rm -rf /var/cache/yum /tmp/*
+
+# python 2 and 3 must be installed separately because yum will ignore/discard python2
+# TODO: For some reason, this makes the build fail after adding the iRODS repo
+#RUN yum check-update -q >/dev/null || { [ "$?" -eq 100 ] && yum update -y; } && \
+RUN yum update -y && \
+    yum install -y \
+        python3 \
+        python3-devel \
+        python3-pip \
+    && \
+    yum clean all && \
+    rm -rf /var/cache/yum /tmp/*
+
+RUN python3 -m pip install unittest-xml-reporting distro psutil pyodbc jsonschema requests
+
 COPY rsyslog.conf /etc/rsyslog.conf
+
+# TODO: For some reason, this makes the build fail after adding the iRODS repo
+#RUN yum check-update -q >/dev/null || { [ "$?" -eq 100 ] && yum update -y; } && \
+RUN yum update -y && \
+    yum install -y \
+        python \
+        python-devel \
+        python-distro \
+        python-pip \
+        python-requests \
+        python-jsonschema \
+        python-psutil \
+    && \
+    yum clean all && \
+    rm -rf /var/cache/yum /tmp/*
+
+RUN python2 -m pip install xmlrunner
 
 RUN mkdir -p /irods_testing_environment_mount_dir && chmod 777 /irods_testing_environment_mount_dir
 
